### ISSUE TITLE
Fetch data from Firestrore and visualize

### ISSUE THREAD

**Issue by abhishekpatel946** [abhishekpatel946/Smart-Vehicle-Fleet-Manager#10]
### **If you want to contribute in then you must be read first CONTRIBUTE.md**

**Problem will be described in [CONTRIBUTE.md](https://github.com/abhishekpatel946/Smart-Vehicle-Fleet-Manager/blob/dashboard/CONTRIBUTE.md)**

**Overview**

> Fetching data from firestore database and render in-app.

> There are 2 things:- 

> -  first the chart for updated with real-time data

> - second will be a log table to keep track of each record and display

**Comment by ielixirz** [comment]
hi, I think I can work on this could you assign me thanks!

**Comment by abhishekpatel946** [comment]
Sure

**Comment by abhishekpatel946** [comment]
> Sure

**If you confused somewhere else then feel free to contact me anytime.**
`abhishekpatel946@gmail.com`

**Comment by abhishekpatel946** [comment]
The #10 issue has been resolved. c1f7d6c9f2f0efd80d4892e2ba54860033b4571a 💫 💥
