### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by abhishekpatel946** [abhishekpatel946/Smart-Vehicle-Fleet-Manager#13]
## Change in README.md file*

**Description**
-  - [ ] describe the problem statement
-  - [ ] how to we solve the probelm

**Road Map**
- - [ ] create our project folder structure

**Installation**
- - [ ] prerequisite
- - [ ] installation guide

**Contribution**
- - [ ] contribution guidelines
- - [ ] define rules for contribution

**Comment by AshutoshMourya** [comment]
I'll do it, assign me!

**Comment by abhishekpatel946** [comment]
Sure! @AshutoshMourya

**Comment by abhishekpatel946** [comment]
e300fa5964119a3ac54b5a3ef8bc13b5e23c498c
