### ISSUE TITLE
Fix the logo

### ISSUE THREAD

**Issue by abhishekpatel946** [abhishekpatel946/Smart-Vehicle-Fleet-Manager#4]
### Put the logo 

- [ ] **inside the navbar before the name "Smart Vehicle Fleet Manager".**

> make sure the size of the logo is doesn't break the navbar.

> logo is always before the name "Smart Vehicle Fleet Manager".

> keep it simple and float at the left side of the navbar.

@MuskanKabir @AshutoshMourya

**Comment by phanlyhuynh** [comment]
Hi. Can you assign to me? Thanks!!!

**Comment by abhishekpatel946** [comment]
hey @phanlyhuynh 
Can you contribute to [Smart Vehicle Fleet Manager](https://github.com/abhishekpatel946/Smart-Vehicle-Fleet-Manager) then I'll assign you another task?

**Comment by MuskanKabir** [comment]
you can assign it to me?

**Comment by AshutoshMourya** [comment]
is it resolved?

**Comment by abhishekpatel946** [comment]
> is it resolved?

Hey @AshutoshMourya you're late it is already assinged.
If you want to contribute in our project stay in touch and try to came early as possible with the better solution for next time.

**Comment by abhishekpatel946** [comment]
> Hi. Can you assign to me? Thanks!!!

Hey, @phanlyhuynh  
If you can fix this issue then I'll assign it to you.

**ping me, then I'll assign you.**

**Comment by MuskanKabir** [comment]
Hi, @abhishekpatel946  Can you assign it to me?
