### ISSUE TITLE
bug arrise in b0606b54d0e7abde5676ba4914b5d339b6c53618

### ISSUE THREAD

**Issue by abhishekpatel946** [abhishekpatel946/Smart-Vehicle-Fleet-Manager#49]
**Describe the bug**

**To Reproduce**
1. Go to `navigation panel`
2. Click on 'all navigation buttons'
3. See all buttons are not working due to `preventDeafault`.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mint20.1]
 - Browser [e.g. chrome]
 - Version [e.g. 89]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhishekpatel946** [comment]
Bug in the b0606b54d0e7abde5676ba4914b5d339b6c53618

**Comment by Muskan-Kabirpanthi** [comment]
got it. :+1:

**Comment by abhishekpatel946** [comment]
Great, Work on it
